import '@radix-ui/themes/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css"
import Navbar from "./Navbar";
import { Theme, ThemePanel } from '@radix-ui/themes';
const inter = Inter({ subsets: ["latin"],
  variable: '--font-inter',
 });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
      <Theme appearance='light' accentColor="green" panelBackground="solid" radius="full">
          <Navbar />
          <main className='p-5'>{children}</main>
          {/* <ThemePanel /> */}
        </Theme>
        </body>
    </html>
  );
}
